export const carsActions = {
  CARS_REQUEST: "CARS_REQUEST",
  CARS_LOADED: "CARS_LOADED",
  CARS_LOAD_ERROR: "CARS_LOAD_ERROR",
};

export const dealersActions = {
  DEALERS_REQUEST: "DEALERS_REQUEST",
  DEALERS_LOADED: "DEALERS_LOADED",
  DEALERS_LOAD_ERROR: "DEALERS_LOAD_ERROR",
  RETURN_FROM_CACHE: "RETURN_FROM_CACHE",
};
